- hosts: all
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: latest


    - name: Start httpd
      service:
        name: httpd
        state: started
        enabled: yes 

   
    - name: install unzip
      yum:
        name: unzip
        state: latest

    
    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      ansible.builtin.unarchive:
        src: https://www.free-css.com/assets/files/free-css-templates/download/page279/tropiko.zip
        dest: /var/www/html
        remote_src: yes
